### PR TITLE
fix(#139): case MarkerPosition, added test

### LINKED ISSUE #139: LineSymbolizer with specified MarkerPlacement has a superfluous GraphicStroke
A LineSymbolizer with a MarkerPlacement "CIMMarkerPlacementAtRatioPositions" or "CIMMarkerPlacementAtExtremities" is converting the markers first as one marker on the line and additionally as LineSymbolizer with a GraphicStroke of the same marker object. This LineSymbolizer is superfluous. If there is a specified MarkerPlacement, the line should not be additionally drawn with this marker as a line symbol.

### PR DESCRIPTION
**Pull request by myriamfischer**
Fix #139

### CODE REVIEW

File: src/processSymbolLayer.ts [hunk 1]
```diff
@@ -93,31 +93,56 @@ const processSymbolLayerWithSubSymbol = (
...
+            const endbothSymbolizer = processOrientedMarkerAtEndOfLine(
+              layer,
+              "end",
+              options,
+            );
+            if (startbothSymbolizer && endbothSymbolizer) {
+              symbolizers.push(startbothSymbolizer);
+              symbolizers.push(endbothSymbolizer);
+            }
+            break;
```
Comment (ger-benjamin) [inline src/processSymbolLayer.ts:136]: That looks working, but I think we can write this `switch` in a more compact way (which is great for maintenance and understandability):

```suggestion
        const processOrientedMarkerAtEndOfLineFn = (position: "start"|"end") => {
            const symbolizer = processOrientedMarkerAtEndOfLine(
              layer,
              position,
              options,
            );
            if (symbolizer) {
                symbolizers.push(symbolizer)
            }
        }
        if (orientedMarkerPosition === "start" || orientedMarkerPosition === "both")
            processOrientedMarkerAtEndOfLineFn("start");
        }
        if (orientedMarkerPosition === "end" || orientedMarkerPosition === "both")
            processOrientedMarkerAtEndOfLineFn("end");
        }
```

**Review by ger-benjamin — COMMENTED** [review]
Looks good, I left one comment, and the CI also left one comment.

File: src/processSymbolLayer.ts [hunk 2]
```diff
@@ -93,31 +93,43 @@ const processSymbolLayerWithSubSymbol = (
...
-        if (endSymbolizer) {
-          symbolizers.push(endSymbolizer);
+
+        if (
+          orientedMarkerPosition === "end" ||
+          orientedMarkerPosition === "both"
+        ) {
+          processOrientedMarkerAtEndOfLineFn("end");
         }
+      } else {
```
Comment (ger-benjamin) [inline src/processSymbolLayer.ts:125]: Is the `else` correct ? With current code, the execution will add a line symbolizer if orientedMarkerPosition is `start` (because the else is for "end" or "both").

Do we need to remplace the `else` by `if (!orientedMarkerPosition) {}` (meaning orientedMarkerPosition is undefined)

In this case you can start with `if (orientedMarkerPosition) {  <current ifs on orientedMarkerPosition> }` then `else { <add lineSymbolizer> )`
